default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Myblog_development


test:
  <<: *default
  database: Myblog_testing

production:
  <<: *default
  database: Myblog_production
  username: damirik
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
